FROM ubuntu:19.04
LABEL maintainer "sunghwan19 <sunghwan519@hotmail.com>"

RUN apt-get update && apt-get install -y \
	build-essential \
	cmake \
	clang-8 \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

COPY . /app

WORKDIR /app/build
RUN cmake .. -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 && \
	make -j "$(nproc)" && \
	make install && \
	bin/UnitTest

WORKDIR /